name: Pull Request
# run on all pull requests on all branches

on:
  pull_request:
    branches:
      - '**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: checkAndDetekt
      - uses: actions/upload-artifact@v3
        with:
          name: reports
          path: |
            androidApp/build/reports
            desktopApp/build/reports
            shared/build/reports
            build/reports