on:
  release:
    types: [ released, prereleased ]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: iosApp:linkReleaseExecutableUikitArm64
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
#      - uses: softprops/action-gh-release@v1
#        with:
#          files: |
#            desktopApp/build/compose/binaries/main-release/**/*.*
#            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}