name: swift-code-coverage

on:
  # run on all pull requests on all branches
  pull_request:
    branches:
      - '**'
      
jobs:
  codecov:
    container:
      image: swift:5.6.1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - run: |
       swift package init --type library
       swift test --enable-test-discovery --enable-code-coverage
    - name: Test coverage
      uses: maxep/spm-lcov-action@0.3.0
      with:
        output-file: ./coverage/lcov.info
